# -*- coding: utf-8 -*-
"""removeSquirrels.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OEJT9YHrS1YolCnJCEdghCgRpwP0AzHr
"""

# !pip install diffusers
# !pip install -q git+https://github.com/huggingface/transformers.git
# !pip install accelerate

import PIL
import requests
import torch
from io import BytesIO
# import diffusers
from diffusers import StableDiffusionInpaintPipeline
from PIL import Image

pipeline = StableDiffusionInpaintPipeline.from_pretrained(
    "runwayml/stable-diffusion-inpainting"
)

pipeline = pipeline.to('cuda')

image_dir = [
    # "/content/drive/MyDrive/Colab Notebooks/Applied ML/Assignment 3/Test_Squirrels/test_squirrel_img_1.jpeg",
    # "/content/drive/MyDrive/Colab Notebooks/Applied ML/Assignment 3/Test_Squirrels/test_squirrel_img_2.jpeg",
    # "/content/drive/MyDrive/Colab Notebooks/Applied ML/Assignment 3/Test_Squirrels/test_squirrel_img_3.jpeg",
    # "/content/drive/MyDrive/Colab Notebooks/Applied ML/Assignment 3/Test_Squirrels/test_squirrel_img_4.jpeg",
    "/content/drive/MyDrive/Colab Notebooks/Applied ML/Assignment 3/Test_Squirrels/test_squirrel_img_5.jpeg"
    
]
mask_dir = [
    # "/content/drive/MyDrive/Colab Notebooks/Applied ML/Assignment 3/Masked_Squirrel/mask_test_squirrel_img_1.jpg",
    # "/content/drive/MyDrive/Colab Notebooks/Applied ML/Assignment 3/Masked_Squirrel/mask_test_squirrel_img_2.jpg",
    # "/content/drive/MyDrive/Colab Notebooks/Applied ML/Assignment 3/Masked_Squirrel/mask_test_squirrel_img_3.jpg",
    # "/content/drive/MyDrive/Colab Notebooks/Applied ML/Assignment 3/Masked_Squirrel/mask_test_squirrel_img_4.jpg",
    "/content/drive/MyDrive/Colab Notebooks/Applied ML/Assignment 3/Masked_Squirrel/mask_test_squirrel_img_5.jpg",
    
]

image_path = image_dir[0]
mask_path = mask_dir[0]
init_image = Image.open(image_path).resize((512, 512))
mask_image = Image.open(mask_path).resize((512, 512))
prompt = 'Replace masked foreground with plant leaves hanging on tree'
image = pipeline(prompt=prompt, image=init_image, mask_image=mask_image).images[0]


image.save("removed_squirrel_output10.jpg")